name: barra_al_salfah
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  change_app_package_name: ^1.5.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5+1
  rename: ^3.1.0
  shared_preferences: ^2.2.2 # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 # Add this line

flutter:
  uses-material-design: true
  assets:
    - assets/categories.json

flutter_launcher_icons:
  android: true
  ios: false # Set to true if you ever build for iPhone
  image_path: "assets/icon.png"
  min_sdk_android: 21 # matches your build.gradle
